/************************************************************
 *Copyright (c) 2013-2015 深圳市赛柏达技术有限公司技术研发部
 *
 *FileName:		log.cpp        
 *Writer:		smart-skynet
 *create Date:  2015/01/01
 *Rewriter:		kason
 *Rewrite Date:	2015/09/28
 *Impact:
 *
 *Main Content(Function Name、parameters、returns)
 *
 ************************************************************/

#include "log.h"
#include <QTextStream>
#include <QDebug>

CLOG::CLOG()
{

}

void CLOG::Log(QString strLog)
{
    // If log file size > 1MB , delete log file

    QFile file("log/monitor.log");
    if (false == (file.open(QIODevice::WriteOnly | QIODevice::Text| QIODevice::Append)))
    {
        QTextStream out(&file);
           out << "This file is generated by Qt\n";
           file.close();
        } else {
          qDebug() << "Error";
        }


//    if(file.size() > MAX_LOG_FILE_SIZE)
//    {
//        file.remove();
//    }

    QDateTime time = QDateTime::currentDateTime();
    QString strTime = time.toString("yyyy-MM-dd hh:mm:ss   ");

    strLog = strTime + strLog + "\r\n";

    file.write(strLog.toLatin1().data(), strLog.length());

    file.close();
}


